name: Deploy Website to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        env:
          SUDO_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: "2204"
          envs: SUDO_PASSWORD
          script: |
            # Navigate to the project directory on the server
            cd /var/www/comfortcasaparadise
            
            # Update the code from GitHub (Make sure git is configured on the server)
            git pull origin main
            
            # Navigate to the backend directory
            cd backend
            
            # Activate the virtual environment (assuming it's in the root or backend folder)
            source venv/bin/activate || source ../venv/bin/activate || echo "No venv found, skipping activation"
            
            # Install backend dependencies
            pip install -r requirements.txt
            
            # Restart the service by providing the sudo password automatically
            echo "$SUDO_PASSWORD" | sudo -S systemctl restart comfortcasa.services
